### ISSUE TITLE
Vertical metrics

### ISSUE THREAD

**Issue by davelab6** [itfoundry/hind-siliguri#1]
In the current OTFs, 

```
<sTypoAscender value="750"/>
<sTypoDescender value="-250"/>
<sTypoLineGap value="200"/>
<usWinAscent value="850"/>
<usWinDescent value="350"/>
```

I believe they should be the family bbox with 0 linegaps, to avoid clipping, as per https://github.com/googlefonts/gf-docs/blob/master/VerticalMetricsRecommendations.md

```
<sTypoAscender value="1116"/>
<sTypoDescender value="-501"/>
<sTypoLineGap value="0"/>
<usWinAscent value="1116"/>
<usWinDescent value="501"/>
```

**Comment by lianghai** [comment]
Will read the recommendations and investigate more before making the change to all Hind families.

**Comment by lianghai** [comment]
Assigned `<1200, -800>` to all Hind projects to make them consistent in vertical metrics.

**Comment by davelab6** [comment]
That sounds good.
